---

# Don't install node/npm from the debian packages; it's too old.
#- include: ../../common/tasks/pkg-install.yml package=nodejs
#- include: ../../common/tasks/pkg-install.yml package=nodejs-legacy
#- include: ../../common/tasks/pkg-install.yml package=npm

- name: unzip node archive
  unarchive:
     src: "{{ downloaded_applications_home }}/node/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
     dest: /opt
     creates: "{{ node_home }}/bin/node"
  become: yes
  tags: debug

- name: create symlink to node executable
  file: src={{ node_home }}/bin/node dest=/usr/local/bin/node owner=root group=root state=link
  become: yes
  tags: debug

- name: create symlink to npm executable
  file: src={{ node_home }}/bin/npm dest=/usr/local/bin/npm owner=root group=root state=link
  become: yes
  tags: debug

