---

# Don't install node/npm from the debian packages; it's too old.
#- include: ../../common/tasks/pkg-install.yml package=nodejs
#- include: ../../common/tasks/pkg-install.yml package=nodejs-legacy
#- include: ../../common/tasks/pkg-install.yml package=npm

- name: unzip node archive
  unarchive:
     src: "{{ downloaded_applications_home }}/node/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
     dest: /opt
     creates: "{{ node_home }}/bin/node"
  become: yes

# TODO this shouldn't be needed, but the npm module in future tasks seems to complain even though the node bin directory is on the PATH below
- name: create symlink to node executable
  file: src={{ node_home }}/bin/node dest=/usr/local/bin/node owner=root group=root state=link
  become: yes

# TODO this shouldn't be needed, but the npm module in future tasks seems to complain even though the node bin directory is on the PATH below
- name: create symlink to npm executable
  file: src={{ node_home }}/bin/npm dest=/usr/local/bin/npm owner=root group=root state=link
  become: yes

- name: add node bin directory to PATH
  template: src=etc/profile.d/node.sh.j2 dest=/etc/profile.d/node.sh owner=root group=root mode=0755
  become: yes
# TODO This will probably require logging-out and logging back in for the bash changes to take effect, which isn't happening right now. Is there a way to source changes in-place during this session?
